USE [master]
GO

/****** Object:  Database [Activities]    Script Date: 19-Dec-2021 12:06:46 PM ******/
DROP DATABASE [Activities]
GO

/****** Object:  Database [Activities]    Script Date: 19-Dec-2021 12:06:46 PM ******/
CREATE DATABASE [Activities]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Activities', FILENAME = N'D:\datadb\MSSQL13.MSSQLSERVER\MSSQL\DATA\Activities.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Activities_log', FILENAME = N'D:\datadb\MSSQL13.MSSQLSERVER\MSSQL\DATA\Activities_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Activities].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Activities] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Activities] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Activities] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Activities] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Activities] SET ARITHABORT OFF 
GO

ALTER DATABASE [Activities] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Activities] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Activities] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Activities] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Activities] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Activities] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Activities] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Activities] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Activities] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Activities] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Activities] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Activities] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Activities] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Activities] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Activities] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Activities] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Activities] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Activities] SET RECOVERY FULL 
GO

ALTER DATABASE [Activities] SET  MULTI_USER 
GO

ALTER DATABASE [Activities] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Activities] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Activities] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Activities] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Activities] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Activities] SET QUERY_STORE = OFF
GO

USE [Activities]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [Activities] SET  READ_WRITE 
GO


